name: Build with Visual Studio 2022

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Clone routine
      run: git clone https://github.com/henrypp/routine.git

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild chrlauncher.sln /m /p:configuration="Release" /p:platform="x64"

    - name: Publish build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: chrlauncher.exe
        path: build/release
